"""Test migration

Revision ID: 9b194076d973
Revises: add_mode_features_2025_09_28
Create Date: 2025-10-01 00:45:42.713017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b194076d973'
down_revision = 'add_mode_features_2025_09_28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_source_domain')
        batch_op.drop_index('ix_conversations_source_platform')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_category')
        batch_op.drop_index('idx_notifications_created_at')
        batch_op.drop_index('idx_notifications_tenant_status')
        batch_op.drop_index('idx_notifications_user_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_user_read', ['user_id', 'read_at'], unique=False)
        batch_op.create_index('idx_notifications_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('idx_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_notifications_category', ['category'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_source_platform', ['source_platform'], unique=False)
        batch_op.create_index('ix_conversations_source_domain', ['source_domain'], unique=False)

    # ### end Alembic commands ###
